# Generated by Django 4.2.2 on 2023-06-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_ckode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lead',
            table='leads',
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
