# Generated by Django 4.2.2 on 2023-06-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ckode', '0002_alter_lead_table_alter_project_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'In Progress'), (2, 'Finished'), (3, 'Closed'), (4, 'Proposal')]),
        ),
    ]
