# Generated by Django 4.2.2 on 2023-06-09 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_ckode', '0004_alter_lead_notes_alter_project_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_ckode.lead'),
        ),
    ]
