# Generated by Django 4.2.2 on 2023-06-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ckode', '0005_user_username_alter_project_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
