# Generated by Django 4.2.2 on 2023-06-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ckode', '0007_alter_user_managers_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
